### ISSUE TITLE
CMake Windows build finding dynamic instead of static dependent libraries?

### ISSUE THREAD

**Issue by ellenjohnson** [libsndfile/libsndfile#617]
Hi all!
  @evpobr -- thank you so much for the 1.0.29 and now 1.0.30 releases!

   We build libsndfile with ogg, vorbis, and flac support, and have built both static and dynamic versions of those libs.  When building libsndfile from source on Windows using CMake, it picks up the dlls for these libraries instead of the static libs.  I can see this because the libsndfile-1.dll size is smaller than expected, indicating it didn't build with the static libraries.  Plus in Linux, doing objdump -p libsndfile-1.dll shows the dependent dlls.

  We use CMake 3.15, so per your instructions I'm using CMAKE_MSVC_RUNTIME_LIBRARY instead of deprecated ENABLE_STATIC_RUNTIME.  I added this temporarily to /cmake/SndFileChecks.cmake to test it out but it didn't work:
   set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

  Is there another flag or CMake setting in libsndfile that I need to set to force it to pick the static libs?
  Thank you!
     ellen

**Comment by evpobr** [comment]
Hi @ellenjohnson 

`ENABLE_STATIC_RUNTIME` and `CMAKE_MSVC_RUNTIME_LIBRARY` are about [system CRT libraries](https://docs.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference?view=vs-2019).

About Ogg, Vorbis, FLAC and Opus dependencies - just use [Vcpkg package manager](https://github.com/microsoft/vcpkg) as described in README.md.

If you really need to do it manually there are some variables to set:

```
OGG_INCLUDE_DIR
OGG_LIBRARY
Vorbis_Vorbis_INCLUDE_DIR
Vorbis_Vorbis_LIBRARY
Vorbis_Enc_INCLUDE_DIR
Vorbis_Enc_LIBRARY
FLAC_INCLUDE_DIR
FLAC_LIBRARY
OPUS_INCLUDE_DIR
OPUS_LIBRARY
```

**Comment by ellenjohnson** [comment]
Hi @evpobr,

Thank you for the info.  We don't use vcpkg -- we're building from source using CMake on Windows.  We've built ogg, flac, and vorbis from source on Windows using CMake and built both static and dynamic libs for those.  Note we don't build with Opus support, so I had to tweak CMakeLists.txt to not intertwine the setting of ENABLE_EXTERNAL_LIBS with whether it finds Opus.

I'm already setting these CMake options:
CMAKEOPTIONS += -DENABLE_EXTERNAL_LIBS=ON \
          -DBUILD_SHARED_LIBS=ON \
          -DENABLE_COMPATIBLE_LIBSNDFILE_NAME=ON \
          -DPYTHON_EXECUTABLE:PATH=$(PYTHON) \
          -DCMAKE_BUILD_TYPE=Release \
          -DOGG_INCLUDE_DIR:PATH=$(OGG_DIR)/include \
          -DOGG_LIBRARY:PATH=$(OGG_DIR)/lib/ogg.lib \
          -DVorbis_Vorbis_INCLUDE_DIR:PATH=$(VORBIS_DIR)/include \
          -DVorbis_Vorbis_LIBRARY:PATH=$(VORBIS_DIR)/lib/vorbis.lib \
          -DVorbis_Enc_INCLUDE_DIR:PATH=$(VORBIS_DIR)/include \
          -DVorbis_Enc_LIBRARY:PATH=$(VORBIS_DIR)/lib/vorbisenc.lib \
          -DVorbis_File_INCLUDE_DIR:PATH=$(VORBIS_DIR)/include \
          -DVorbis_File_LIBRARY:PATH=$(VORBIS_DIR)/lib/vorbisfile.lib \
          -DFLAC_INCLUDE_DIR:PATH=$(FLAC_DIR)/include \
          -DFLAC_LIBRARY:PATH=$(FLAC_DIR)/lib/flac.lib

But it's still picking up the dlls instead of the .libs.
Is there something else I'm missing?
Thank you!

**Comment by evpobr** [comment]
> We don't use vcpkg -- we're building from source using CMake on Windows.

Hmm. Vcpkg builds packages from sources. Using CMake.

**Comment by evpobr** [comment]
Anyway i need more info. Your OS, compiler, CMake configure output, CMakeCache.txt.

**Comment by krisfed** [comment]
Hi @evpobr - thank you for your response! We (I am working with @ellenjohnson ) were able to resolve this - turned out we were trying to use import libs instead of static libs..

On the topic of ENABLE_STATIC_RUNTIME/CMAKE_MSVC_RUNTIME_LIBRARY - could you clarify the recommendation in README.md to set ENABLE_STATIC_RUNTIME=ON to remove the dependencies on CRT DLLs? We are trying to decide whether to move forward linking to CRT libraries statically or dynamically (we were able to successfully build both ways), and it would help to understand why static linking is recommended.

Thanks for your time!

**Comment by evpobr** [comment]
Sounds reasonable.

**Comment by krisfed** [comment]
So could you please share any insights about why it is recommended in the README to use static linking for CRT libraries? It would be much appreciated!

**Comment by evpobr** [comment]
@krisfed, check updated version please:

### Notes for Windows users

#### System CRT library

First advice about Visual Studio [system CRT libraries](https://docs.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference?view=vs-2019),
it is system code linked as static or dynamic library to every C application.

You can find related option in Visual Studio project properties:

    C/C++ -> Code Generation -> Runtime Library

Dynamic version of system CRT library is defaut and it means that end user needs
to have the same runtime library installed on his system. Most likely it is so,
but if it is not, the user will see this error message using libsndfile DLL:

    "The program can't start because <crt-dll-name>.dll is missing from your computer. Try reinstalling the program to fix this problem. "

To avoid this, you may want to enable static CRT library linking. In this case
the size of your DLL will increase slightly the size will increase slightly, but
you can redistribute the libsndfile DLL without having to install the correct
version of the system CRT library.

CMake project will use dynamic system CRT libraries by default, just like
Visual Studio does. But you can change it using `ENABLE_STATIC_RUNTIME` or
`CMAKE_MSVC_RUNTIME_LIBRARY` options.

**Note**: You cannot use both options at the same time, it will lead to a
configuration error.

If you have CMake >= 3.15 you should use
[`CMAKE_MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/v3.15/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) option.

This will enable static linking:

    cmake .. -D"MultiThreaded$<$<CONFIG:Debug>:Debug>"

You can use libsndfile `ENABLE_STATIC_RUNTIME` option to to control CRT library
linking for CMake project: `OFF` or unset (default) for dynamic, and `ON` for
static linking:

    cmake .. -DENABLE_STATIC_RUNTIME=ON

**Note**: This option is deprecated and may be removed in far future because we
have standard option `CMAKE_MSVC_RUNTIME_LIBRARY` now.

#### Using Vcpkg package manager

Second advice is about Ogg, Vorbis FLAC and Opus support. Searching external
libraries under Windows is a little bit tricky. The best way is to use
[Vcpkg](https://github.com/Microsoft/vcpkg). You need to install static libogg,
libvorbis, libflac and libopus libraries:

    vcpkg install libogg:x64-windows-static libvorbis:x64-windows-static
    libflac:x64-windows-static opus:x64-windows-static libogg:x86-windows-static
    libvorbis:x86-windows-static libflac:x86-windows-static opus:x86-windows-static

Then and add this parameter to cmake command line:

    -DCMAKE_TOOLCHAIN_FILE=<path-to-vcpkg>/scripts/buildsystems/vcpkg.cmake

You also need to set `VCPKG_TARGET_TRIPLET` because you use static libraries:

    -DVCPKG_TARGET_TRIPLET=x64-windows-static

**Comment by krisfed** [comment]
Got it, thank you for the details!
