### ISSUE TITLE
Is sndfile-metadata-set set license error?

### ISSUE THREAD

**Issue by zodf0055980** [libsndfile/libsndfile#688]
Hello, I try to use `sndfile-metadata-set` with `--str-license`, but `sndfile-metadata-get` print License is NULL.

This is a file I try : [poc.zip](https://github.com/libsndfile/libsndfile/files/5833316/poc.zip)

```
➜  programs git:(master) ✗ ./sndfile-metadata-set --str-album ww --str-license Apache-2.0 ~/Downloads/poc ./out
➜  programs git:(master) ✗ ./sndfile-metadata-get ./out                                                        
Description            : 
Originator             : 
Origination ref        : 
UMID                   : 
Origination date       : 
Origination time       : 
Loudness value         :   0.00
Loudness range         :   0.00
Max. true peak level   :   0.00
Max. momentary level   :   0.00
Max. short term level  :   0.00
Coding history         : 
Name                   : 
Copyright              : 
Artist                 : 
Comment                : 
Create date            : 
Album                  : ww
License                : 
➜  programs git:(master) ✗ ./sndfile-metadata-get --str-license ./out                                          
License                : 
```

Is this correct?

**Comment by evpobr** [comment]
@zodf0055980 , thanks for issue.  I guess the problem is here:

https://github.com/libsndfile/libsndfile/blob/2221cbedd7abc311882e101078049e94b2968082/src/wavlike.c#L1130-L1176

No `SF_STR_LICENSE` here. Not sure about WAV format, probably this this particular tag value is not supported. But `SF_STR_COPYRIGHT` is supported, is this the same for you?

@erikd, can you explain this?

**Comment by zodf0055980** [comment]
Thanks a lot, I will try to use SF_STR_COPYRIGHT.
And I found the `api.md` table typo in #690.
