### ISSUE TITLE
1.1.0 official release ? 

### ISSUE THREAD

**Issue by MT2017090** [libsndfile/libsndfile#799]
Thank you for adding MP3 support to 1.1.0 beta version. Unfortunately, we are restrained to use only official releases, so we are eagerly waiting for the official 1.1.0 release to use the new MP3 functionality and for resolving an open CVE ( https://github.com/libsndfile/libsndfile/issues/687 ) When is the official 1.1.0 release expected to be out?

**Comment by evpobr** [comment]
Hi @MT2017090 . No due date yet. Waiting for @arthurt. We don't have many developers, so we try not to bother them once again with questions when it's ready.

So we'll have to wait for now. After 1.1.0, we will change our development workflow so that we can release bugfixes and minor releases while long-term feature development is underway.

**Comment by MT2017090** [comment]
Thank you and we understand your concerns about the lack of developers. Let us know if we could be of any help in accelerating the development work from our side. We would be glad to help you out!
