### ISSUE TITLE
V1.1.0 compiles 1.0.34 shared lib

### ISSUE THREAD

**Issue by riban-bw** [libsndfile/libsndfile#841]
After checking out 1.1.0 from github and running `make` a file called `src/.libs/libsndfile.so.1.0.34` is created. I would expect it to be `src/.libs/libsndfile.so.1.1.0`. This is on raspbian buster.

**Comment by evpobr** [comment]
Hi @riban-bw , it is correct. 1.1.0 is API version, 1.0.34 is ABI version.

**Comment by riban-bw** [comment]
So, is this actually version 1.0.34, as one would understand it in a Debian distribution? (Confusing!)

**Comment by evpobr** [comment]
As I understand it, you are confused that the package (API) version does not match the version in the file name (ABI), as it was before.

In fact, the coincidence of API and ABI versions is rather an accident or an intentional simplification (as it was in our case).

Now the behavior has changed (#652). The reason is simple, we want versioning according to the available standards ([SemVer](https://semver.org/), [Libtool versioning](https://www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html)).

You need API version (1.1.0). Don't look at ABI version encoded in filename, it is for OS.

Some proofs that versions can be different:

```
libogg0 (1.3.2-1) -> libogg.so.0.8.2
libopus0 (1.3.1-0.1) -> libopus.so.0.8.0
libvorbis0a (1.3.7-1) -> libvorbis.so.0.4.9
```

**Comment by riban-bw** [comment]
Okay so I should package this up as v1.1.0 which includes libsndfile.so.1.0.34. Cheers!
