### ISSUE TITLE
libsndfile (soundfile) for mp3 not float32 but float64

### ISSUE THREAD

**Issue by magicse** [libsndfile/libsndfile#880]
Link to issue [libsndfile (soundfile) for mp3](https://github.com/bastibe/python-soundfile/issues/349)
Audio out from libsndfile (soundfile) for mp3 not float32 but float64.
Because of this, if we do not force the dtype=float64 , we get an empty array

print mp3 with dtype set float32 by default
audio_test, _ = librosa.load('./g.mp3', mono=False, res_type='kaiser_fast',sr=sr)
```
[]
0
(2, 0)
tensor([], size=(2, 0))
```
print mp3 with dtype =float64
audio_test, _ = librosa.load('./g.mp3', mono=False, res_type='kaiser_fast',sr=sr, dtype=np.float64)
```
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
21182464
(2, 10591232)
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
```

**Comment by MmAlder** [comment]
dtype specifies the type of the data that is returned.  It does not necessarily match the datatype of the file.

The reason for the different behavior is because the _cdata_io method of the SoundFile class in python-soundfile/soundfile.py  calls either sf_readf_float or sf_readf_double in libsndfile/src/sndfile.c which in turn call mpeg_dec_read_f or mpeg_dec_read_d respectively in libsndfile/src/mpeg_decode.c.  Both call mpeg_dec_decode in libsndfile/src/mpeg_decode.c, but mpeg_dec_read_d makes multiple calls as it translates floats to doubles in a buffer.  Both types miss the last call, but for floats there is only one call, so nothing is returned.  For doubles, the result is truncated as the last buffer is not returned.

The reason appears to be that mpg123_read in libmpg123/src/libmpg123/libmpg123.c returns MPG123_DONE when it reaches the end-of-file, but mpeg_dec_decode treats it as an error.

Note that you can read either as floats or doubles by specifying a duration that is sufficiently less than the file length, since that does not require going to end-of-file.

**Comment by evpobr** [comment]
Hi @magicse , @MmAlder .

@arthurt , is there something we can fix?

**Comment by magicse** [comment]
on some mp3 files, dtype=float32 return empty array.  For example file for test [abba](https://github.com/librosa/librosa/files/9674303/abba.zip)

**Comment by arthurt** [comment]
*sigh* So, this was based on an assumption on my part, that libmpg123 was sane an followed the usual way of signalling end of stream. It does not. Easy fix.
